### ISSUE TITLE
Allow Playbooks and different games

### ISSUE THREAD

**Issue by gamefiend** [gamefiend/apocalyptica#12]
Before getting too far in, need to refactor the program to incorporate games and playbooks.

Basic steps:
- [ ] brainstorm new design
- [ ] write tests for expected ouputs
- [ ] refactor to incorporate new design and pass tests
- [ ] test dev environment
- [ ] 🚢 and 🍨 !

/cc @TriskalJM -- super late with this!

**Comment by TriskalJM** [comment]
How's the new design's brainstorming going?
