### ISSUE TITLE
Review of Documentation.

### ISSUE THREAD

**Issue by gamefiend** [gamefiend/apocalyptica#16]
Looking to get feedback on the following documents:

- [Registering Apocalyptica](https://github.com/gamefiend/apocalyptica/blob/master/docs/register.md)
- [Deploying Apocalyptica](https://github.com/gamefiend/apocalyptica/blob/master/docs/deploying.md) ⚠️ 
- [Games and Playbook Format](https://github.com/gamefiend/apocalyptica/blob/master/docs/game-playbook.md) ⚠️ 

> :memo: No need to **try** the steps in any document marked with :warning:.

For each document, it would be helpful to know:

- A rating (1-5) on how **technical** the documentation assumes. See **Technical Rating**, below. Please give 1-2 sentences explaining your rating.
- what places are too vague; where does the document lose you? 
- what would you like more detail or explanation on?
- is any of the phrasing potentially offensive or unsettling?

## Technical Ratings

When rating how technical a document is, use this scale:

**1** - can be picked up by anyone with a computer and a browser (bare minimum to even use this); more process-oriented, with no specific technology required. Almost no specialist jargon.
**2** - requires someone comfortable with the basics of 1-3 technologies to understand information as is. Light jargon with explanation/reference 
**3** - requires working knowledge of 3 or more different technologies before coming into the documentation to use it efficiently. Moderate jargon, possibly a lot of reference.
**4** -  requires a deep conceptual and experiential of one or more technologies to make use of the documentation. Heavy jargon, some reference.
**5** - academic research paper; built on multiple layers of technical assumption. Dense jargon, ihgh reference and contextual assumptions

These ratings aren't **judgements**. Academic research papers have necessary and important audiences. It isn't efficient to retread the basics for experienced professionals, and it wastes everyone's time to supply a non-expert, non-professional with very dense and specifics-filled documentation. 

Your rating will help us 'rightsize' the documentation to its audience.

---

I've tried to write with an eye towards answering all of the above questions well, but need feedback from others to honestly assess that.

**Comment by TriskalJM** [comment]
Just read through _Registering Apocalyptica_. I'd give it a **2** on the scale. It assumes that the person knows the configuration of a Discord server. Specifically, the location of the `env_discord.sample` file. This may be unavoidable, but it's something to keep in mind.
