### ISSUE TITLE
keeps clogging up notifications

### ISSUE THREAD

**Issue by unikirin** [gamefiend/apocalyptica#4]
Very much unsure of the cause here, but in the server I've got Apocalyptica in it keeps intermittently posting its intro spiel in every channel at once, unprompted (making everyone's notifications blow up). It's happened three times since inviting the bot to the server yesterday.

**Comment by gamefiend** [comment]
Part of that is the current test deployment is having problems with restarting on occasion. The restart makes it do its introduction again.  I will likely turn off the notifications for now until I get a way to manage that better.  I will likely need to track servers the bot has been invited to and track announcements.  This might take me a little bit, but I'll keep this issue up to date.

But again, for the time being: **notifications off** on Apolyptica.

Thanks!

**Comment by gamefiend** [comment]
update: I've set a flag for notifications on Apocalyptica, and that change is being rolled out tonight. I'll close this issue for now, as I won't be doing anything fancy with the Intro notification for some time.

Thanks!
