### ISSUE TITLE
Possible Slack version?

### ISSUE THREAD

**Issue by TheNathanBlack** [gamefiend/apocalyptica#6]
Hey! 

This is awesome, is love to be able to run it on slack too!

**Comment by gamefiend** [comment]
Thanks! This is definitely possible. There are a few things I need to take care of first, but I'll update this when and if anything changes.  The biggest concern for me is to find the balance between forking (could easily rewrite for slack, but then we have two codebases) and refactoring (building it so one codebase works for multiple services is ideal but requires more design work). 

I think the work involved would look something like ( following list is really me thinking out loud a bit about the work to capture, not an attempt to show that is particularly involved :) ) : 

- [ ] research slack go client libraries
- [ ] make test fork in slack (it could go on this way for some time, but potential drift makes me nervous)
- [ ] abstract event code with interfaces, refactor slack and discord code into their own packages that implement the interfaces 
- [ ] implement client connect code, implementing each client in its own separate goroutine and context.
- [ ] add command line arguments to allow selection
- [ ] tests.  (I should write this earlier, but I am a terrible human in this way)

Anyways, glad you like, and all this verbiage is just me leaving a paper trail for future me and/or contributors. Thanks for the feedback!
